imports_layout = "Vertical"
force_multiline_blocks = true
edition = "2021"
brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"
fn_call_width = 60
fn_args_layout = "Vertical"
max_width = 80
closure_block_style = "AlwaysNextLine"
closure_block_indent_threshold = 0
blank_lines_lower_bound = 0
blank_lines_upper_bound = 1