imports_indent = "Block"
imports_layout = "Vertical"
fn_params_layout = "Vertical"
merge_imports = true
force_multiline_blocks = false
match_arm_blocks = false
match_block_trailing_comma = true
edition = "2021"
brace_style = "SameLineWhere"
control_brace_style = "AlwaysSameLine"
fn_call_width = 60
fn_args_layout = "Vertical"
max_width = 80
blank_lines_lower_bound = 0
blank_lines_upper_bound = 1