[config]
skip_core_tasks = true
default_to_workspace = false

[tasks.default]
dependencies = ["test"]

[tasks.test]
description = "Test"
command = "cargo"
args = ["test", "${@}"]

[tasks.build]
description = "Build"
command = "cargo"
args = ["build", "${@}"]

[tasks.clean]
description = "Clean"
command = "cargo"
args = ["clean"]
