
[workspace]
resolver = "2"
members = [
  "context-search",
  "context-insert",
  "context-read",
  "context-trace",
]


[profile.dev]
debug = true
opt-level = 0

[profile.release]
opt-level = 2 # fast and small wasm
