use crate::traversal::state::{
    child::{
        batch::ChildMatchState::{
            Match,
            Mismatch,
        },
        PathPairMode::{
            GraphMajor,
            QueryMajor,
        },
        TDNext::{
            MatchState,
            Prefixes,
        },
    },
    end::{
        EndKind,
        EndReason,
        EndState,
    },
    parent::ParentState,
    BaseState,
};
use batch::{
    ChildModeCtx,
    PathPairMode,
    TDNext,
};
use context_trace::{
    graph::vertex::{
        location::child::ChildLocation,
        wide::Wide,
    },
    impl_cursor_pos,
    path::{
        accessors::{
            has_path::HasRootedRolePath,
            role::{
                End,
                Start,
            },
            root::GraphRoot,
        },
        mutators::{
            adapters::IntoAdvanced,
            lower::PathLower,
            move_path::advance::Advance,
        },
        structs::rooted::index_range::IndexRangePath,
        GetRoleChildPath,
    },
    trace::{
        cache::key::{
            directed::{
                down::DownKey,
                up::UpKey,
                DirectedKey,
            },
            props::{
                CursorPosition,
                LeafKey,
                RootKey,
                TargetKey,
            },
        },
        has_graph::HasGraph,
    },
};
use derive_more::{
    derive::Deref,
    DerefMut,
};
use std::{
    cmp::Ordering,
    collections::VecDeque,
    fmt::Debug,
};
use tracing::debug;
